### ISSUE TITLE
IDE Integration - PHPStorm

### ISSUE THREAD

**Issue by ryanwelcher** [10up/phpcs-composer#10]
I installed this for an existing project to be used with `lint-staging` and while the automated process worked great, I was not able to get PHPStrom to use the ruleset for inline notifications.

Using the instructions in the readme,  I was getting errors similar to #9.

I was able to get PHPStorm to indicate the same errors inline that are flagged it the scan by creating a custom `ruleset.xml` file that contained only the rules contains in the 10up-Default/ruleset.xml file of this repo.

I'm not sure if this is specific to my setup ( I have wpcs setup globally ) but wanted to flag it. Perhaps, we just need to update the readme to address this edge-case?

**Comment by sudar** [comment]
@ryanwelcher 

Did you manage to get the PhpStorm integration working?

I am facing the same problem that you are facing while integrating phpcs with PhpStorm and wasted a couple of hours in trying different things :(

**Comment by nicholasio** [comment]
There are serious issue with paths in the way this was setup.

For example running ./vendor/bin/phpcs -i lists the conding standards set by this package. However running phpcs directly from ./vendor/bin does not.

```
$ nicholas_io (wp-content) : ./vendor/bin/phpcs -i
The installed coding standards are MySource, PEAR, PSR1, PSR12, PSR2, Squiz, Zend, 10up-Default, WordPress, WordPress-Core, WordPress-Docs, WordPress-Extra and WordPress-VIP
$ nicholas_io (wp-content): cd ./vendor/bin/
$ nicholas_io (wp-content/vendor/bin): ./phpcs -i
The installed coding standards are MySource, PEAR, PSR1, PSR12, PSR2, Squiz and Zend
```

**Comment by tlovett1** [comment]
CC @ChaosExAnima

**Comment by sudar** [comment]
@ryanwelcher @nicholasio @ChaosExAnima 

I managed to fix the compatibility issue with PhpStorm and global phpcs by using the DealerDirect Composer PHPCS plugin to set the included paths config and default ruleset config for phpcs.

My PR is #16 

Please try out the new branch and let me know if this fixes the PhpStorm issue

**Comment by ChaosExAnima** [comment]
Don't have PhpStorm, so I can't Q/A here unfortunately.
