### ISSUE TITLE
Using PHPCompatibilityWP

### ISSUE THREAD

**Issue by samikeijonen** [10up/phpcs-composer#12]
Should we switch using [PHPCompatibilityWP](https://github.com/PHPCompatibility/PHPCompatibilityWP) which takes care of this:

> This WordPress specific ruleset prevents false positives from the PHPCompatibility standard by excluding back-fills and poly-fills which are provided by WordPress.

**Comment by jrfnl** [comment]
Yes, you should ;-)

**Comment by samikeijonen** [comment]
This is closed via #17.
