### ISSUE TITLE
Pull TestVersion out of ruleset

### ISSUE THREAD

**Issue by samikeijonen** [10up/phpcs-composer#19]
PHPCS allows [overruling `TestVersion` only using command-line](https://github.com/10up/phpcs-composer/pull/17#issuecomment-457922189). We currently have PHP 7.0 in our ruleset.

This is problematic when IDE doesn't respect linting if we need to change version to PHP 7.2 for example.

There is [workaround by adding custom ruleset](https://github.com/squizlabs/PHP_CodeSniffer/issues/2197) but I don't think IDE respect that either.

What we could do is pull out `TestVersion` out of 10up ruleset, and always set it on project level. For example in theme and plugin scaffold as a first steps.

**Comment by adrianduffell** [comment]
+1

The default value of `7.0-` is also restrictive since it prevents new features in PHP 7.1 - 7.4 being used.

Another approach would be to set this value to the latest PHP version. This would help flag future compatibility issues when a project is not currently using the latest version of PHP.

**Comment by claytoncollie** [comment]
This PR helps a little bit #31 but I do like the idea of bumping all the way to 8.1
