### ISSUE TITLE
Add additional sniffs

### ISSUE THREAD

**Issue by darylldoyle** [10up/phpcs-composer#28]
**Is your enhancement related to a problem? Please describe.**
There are a number of common issues that the core WP PHPCS rules don't pick up on but that would be beneficial to check in order to catch some low hanging fruit that comes up in code reviews. 

**Describe the solution you'd like**
It seems that A8C have already written custom sniffs for some of these. I propose that we pull these sniffs into our PHPCS rules.

The following sniffs would be good to include from security perspective:

* [Require `exit;` after a `wp_redirect()` or `wp_safe_redirect()` call](https://github.com/Automattic/VIP-Coding-Standards/blob/develop/WordPressVIPMinimum/Sniffs/Security/ExitAfterRedirectSniff.php)
* [Check that the proper escaping function is being used for the context](https://github.com/Automattic/VIP-Coding-Standards/blob/develop/WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php)

**Comment by claytoncollie** [comment]
Merged. Closing.
