### ISSUE TITLE
Add support for PHP 8.2

### ISSUE THREAD

**Issue by claytoncollie** [10up/phpcs-composer#45]
### Is your enhancement related to a problem? Please describe.

Add support for sniffing at PHP 8.2

 Similar to this merged PR https://github.com/10up/phpcs-composer/pull/35

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by darylldoyle** [comment]
This will be included in the `3.0.0` release via #49

**Comment by darylldoyle** [comment]
Fixed in #49
