### ISSUE TITLE
Followed instructions in readme but it installs 3.0.0-RC2

### ISSUE THREAD

**Issue by dkotter** [10up/phpcs-composer#50]
### Describe the bug

Was testing out the recent 3.0.0 release on a project (thanks for all the hard work getting this out!) and in following the instructions in the readme, things weren't working.

We previously had installed this tool from `dev-master`. I followed the instructions in the readme and ran `composer require --dev 10up/phpcs-composer:"~3"`.

I then tried running linting, both with `composer run lint` and with `./vendor/bin/phpcs .` and neither worked. In looking closer, the `phpcs` script didn't exist. I thought maybe there were additional dependencies we now needed to install ourselves (like `squizlabs/php_codesniffer`) but in looking closer, running that command had installed the 3.0.0-RC2 version of this library, instead of the actual released 3.0.0 version.

I was able to fix this by running `composer require --dev 10up/phpcs-composer:"^3"` instead. Not sure if we should update our instructions to use that or if there's something we need to do with those RC tags to get this to install correctly with the current instructions.

### Steps to Reproduce

1. Run `composer require --dev 10up/phpcs-composer:"~3"`
2. Try running `./vendor/bin/phpcs .` and note it fails
3. Inspect the `composer.lock` file and see it installed the 3.0.0-RC2 version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by claytoncollie** [comment]
FWIW, I installed with the exact version number `3.0.0`, not `~3` or even `^3`, and it worked well. I changed the version number in my composer.json, deleted the lock file, and ran `composer install` 

Probably would be good to update the documentation from `~` to `^` or only the version number.

**Comment by darylldoyle** [comment]
Hmm, `~` should work, but I agree that it works in a strange way in composer. The `^` operator is much cleaner and we should update the install instructions to that. Thanks for flagging @dkotter!
